(ns aoc2025.day-7-test
  (:require [aoc2025.day-7 :as sut]
            [clojure.test :as t]
            [clojure.string :as str]))

(def input (str/trim "
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"))

(t/deftest test-walk
  (t/are
      [expected-hits expected-beams hits beams row]
      (= [expected-hits expected-beams] (sut/walk [hits beams] row))
    #{[7 2]} #{6 8} #{} #{7} [[7 2]]
    #{[7 2] [8 4] [6 4]} #{5 7 9} #{[7 2]} #{6 8} [[8 4] [6 4]]
    ))

(t/deftest test-part-1
  (t/is (= 21 (sut/part-1 input))))
